name: DockerHub CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "6UHz383_A).94zd" | docker login -u "sohammjoshi" --password-stdin

      - name: Build Docker image with debug output
        run: |
          # Print the Dockerfile content for debugging
          echo "Dockerfile contents:"
          cat Dockerfile

          # Build with verbose output
          docker build --no-cache -t sohammjoshi/dwm_project:latest . || (echo "Build failed with exit code: $?" && exit 1)

      - name: Push Docker image
        run: docker push sohammjoshi/dwm_project:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted # This will use your EC2-based runner

    steps:
      - name: Deploy directly on self-hosted runner
        run: |
          # Check Docker status
          sudo systemctl status docker

          # Pull the latest image
          docker pull sohammjoshi/dwm_project:latest

          # Stop and remove existing container if it exists
          docker stop dwm_project || true
          docker rm dwm_project || true

          # Run new container
          docker run -d -p 80:5000 --name dwm_project sohammjoshi/dwm_project:latest

          # Verify container is running
          docker ps | grep dwm_project
