name: DockerHub CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "6UHz383_A).94zd" | docker login -u "sohammjoshi" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t sohammjoshi/dwm_project:latest .
          docker push sohammjoshi/dwm_project:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted # This will use your EC2-based runner

    steps:
      - name: Deploy directly on self-hosted runner
        run: |
          # Pull the latest image
          docker pull sohammjoshi/dwm_project:latest

          # Stop and remove existing container if it exists
          docker stop dwm_project || true
          docker rm dwm_project || true

          # Run new container
          docker run -d -p 80:5000 --name dwm_project sohammjoshi/dwm_project:latest

          # Verify container is running
          docker ps | grep dwm_project || echo "Container not running!"
          docker logs dwm_project
